name: Deploy Firebase Functions on merge
on:
  push:
    branches:
      - main

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies (functions)
        run: npm install --prefix server/functions

      - name: Build functions
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CORS_ORIGINS: ${{ secrets.CORS_ORIGINS }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          FIREBASE_STORAGE_SA: ${{ secrets.FIREBASE_STORAGE_SA }}
        run: npm run build --prefix server/functions

      - name: Deploy functions only (using Firebase CLI)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SLG100_F40EB }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only functions --project slg100-f40eb --config server/firebase.json
