name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --prefix server/functions

      - name: Build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CORS_ORIGINS: ${{ secrets.CORS_ORIGINS }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          FIREBASE_STORAGE_SA: ${{ secrets.FIREBASE_STORAGE_SA }}
        run: npm run build --prefix server/functions

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SLG100_F40EB }}
          projectId: slg100-f40eb
